### PR TITLE
Fix for issue #28

### PR DESCRIPTION
**Pull request by mostmark**
Added a helper method to create a RegistryClient with or without security credentials. Security credentials are needed to be able to use the example against a Red Hat OpenShift Service Registry instance.

### CODE REVIEW

**Review by EricWittmann — APPROVED** [review]
This seems reasonable to me.  But I would defer to @carlesarnal on this.

**Comment by EricWittmann** [comment]
I've merged this, but @carlesarnal if you think it should be done differently we can obviously change it later. :)

**Comment by carlesarnal** [comment]
Sorry, I missed this one. Yes, this is reasonable, is very similar to the code present in other examples.

**Comment by EricWittmann** [comment]
I've had to fix it based on the latest registry release - @carlesarnal could you review that and make sure it's OK?

https://github.com/Apicurio/apicurio-registry-examples/blob/master/jsonschema-validation/src/main/java/io/apicurio/registry/examples/validation/json/JsonSchemaValidationExample.java#L151-L152

**Comment by carlesarnal** [comment]
Makes perfect sense, yes.

**Pull request merged**
