### PR TITLE
Updated the examples to the latest 2.0.0 version of registry

### PR DESCRIPTION
**Pull request by EricWittmann**

### CODE REVIEW

**Review by carlesarnal — APPROVED** [review]
LGTM

**Comment by EricWittmann** [comment]
@carlesarnal I'll need you to update the `HeadersLoggingDemo` example.  I basically commented it out so that everything would build. :)

**Comment by carlesarnal** [comment]
> @carlesarnal I'll need you to update the `HeadersLoggingDemo` example. I basically commented it out so that everything would build. :)

Ok, will do it ASAP.

**Comment by famartinrh** [comment]
I've just tested all the examples, all working except `ConfluentSerdesExample` that needs a fix in the api url, but I can fix that later.
however I don't have permissions for merging this. @EricWittmann

**Review by carlesarnal — APPROVED** [review]

**Comment by EricWittmann** [comment]
Fixed, thanks.  Merging now.

**Comment by EricWittmann** [comment]
@famartinrh Note that I made some changes to the Serdes artifact resolver to make it easier to create a custom resolver.  FYI.

**Pull request merged**
